name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (if necessary)
      run: sudo apt-get install autoconf # or other dependencies

    - name: Generate configure script (if necessary)
      run: |
        chmod +x autogen.sh
        ./autogen.sh

    - name: Configure
      run: |
        chmod +x configure
        ./configure

    - name: Make
      run: make

    - name: Make check
      run: make check

    - name: Make distcheck
      run: make distcheck

